# opencv kütüphanesini içe aktaralım
# ...

# matplotlib kütüphanesini içe aktaralım
# ...

# resmi siyah beyaz olarak içe aktaralım
# ...

# resmi çizdirelim
# ...

# resmin boyutuna bakalım
# ...

# resmi 4/5 oranında yeniden boyutlandıralım ve resmi çizdirelim
# ...
# ...

# orjinal resme bir yazı ekleyelim mesela "kopek" ve resmi çizdirelim
# ...
# ...

#  orjinal resme 50 threshold değeri üzerindekileri beyaz yap altındakileri siyah yapalım, 
# binary threshold yöntemi kullanalım ve resmi çizdirelim
# ...
# ...

# orjinal resme gaussian bulanıklaştırma uygulayalım ve resmi çizdirelim
# ...
# ...

# orjinal resme Laplacian  gradyan uygulayalım ve resmi çizdirelim
# ...
# ...

# orhinal resmin histogramını çizdirelim
# ...
# ...


